[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "i2g"
version = "0.1.0"
description = "Convert images to graphs"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "numpy",
    "pillow",
    "networkx"
]
